name: hsfm
channels:
  - conda-forge
dependencies:
  - affine=2.3.0=py_0
  - appnope=0.1.0=py37hc8dfbb8_1001
  - astroid=2.3.3=py37_1
  - astropy=4.0=py37h0b31af3_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.3=pyh8c360ce_0
  - bokeh=1.3.4=py37_0
  - boost-cpp=1.70.0=hd59e818_1
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h0ab9d94_1001
  - cartopy=0.17.0=py37hdb866aa_1005
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37h356ff06_0
  - cfitsio=3.470=h84d2f63_2
  - cftime=1.1.1.1=py37h10e2902_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.3.0=py_0
  - cmocean=2.0=py_3
  - colorcet=2.0.1=py_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - contextily=1.0rc2=py_0
  - cryptography=2.8=py37he655712_2
  - curl=7.68.0=h8754def_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37h0b31af3_0
  - dask=2.3.0=py_0
  - dask-core=2.3.0=py_0
  - datashader=0.10.0=py_0
  - datashape=0.5.4=py_1
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_3
  - distributed=2.3.2=py_1
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=h4a8c4bd_2
  - ffmpeg=4.1.3=h5c2b479_0
  - fiona=1.8.6=py37h39889d8_4
  - fontconfig=2.13.1=h1027ab8_1000
  - freetype=2.10.1=h8da9a1a_0
  - freexl=1.0.5=h1de35cc_1002
  - fsspec=0.6.3=py_0
  - gdal=2.4.2=py37h39889d8_5
  - geographiclib=1.50=py_0
  - geopandas=0.5.1=py_0
  - geopy=1.21.0=py_0
  - geos=3.7.2=h6de7cb9_2
  - geotiff=1.5.1=h83de174_2
  - geoviews=1.6.3=py_0
  - geoviews-core=1.6.3=py_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - giflib=5.1.7=h01d97ff_1
  - glib=2.58.3=py37h7c187be_1003
  - gmp=6.2.0=h4a8c4bd_2
  - gnutls=3.6.5=h53004b3_1002
  - graphite2=1.3.13=h12caacf_1001
  - harfbuzz=2.4.0=h92b87b8_1
  - haversine=2.1.2=py_0
  - hdf4=4.2.13=h84186c3_1003
  - hdf5=1.10.5=nompi_h3e39495_1104
  - heapdict=1.0.1=py_0
  - holoviews=1.12.5=py_0
  - hvplot=0.4.0=py_1
  - icu=58.2=h0a44026_1000
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - importlib-metadata=1.5.0=py37hc8dfbb8_1
  - importlib_metadata=1.5.0=1
  - ipykernel=5.2.0=py37h43977f1_0
  - ipython=7.13.0=py37hc8dfbb8_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37hc8dfbb8_1
  - jasper=1.900.1=h636a363_1006
  - jedi=0.16.0=py37hc8dfbb8_1
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h1de35cc_1001
  - json-c=0.13.1=h1de35cc_1001
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.0=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - kealib=1.4.12=h2324030_0
  - kiwisolver=1.1.0=py37ha1cc60f_1
  - krb5=1.16.4=h1752a42_0
  - lame=3.100=h1de35cc_1001
  - lazy-object-proxy=1.4.3=py37h9bfed18_2
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.68.0=h709d2b2_0
  - libcxx=9.0.1=1
  - libdap4=3.20.4=habf5908_0
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h4a8c4bd_1007
  - libgdal=2.4.2=he37cffe_5
  - libgfortran=4.0.0=2
  - libiconv=1.15=h0b31af3_1006
  - libidn2=2.3.0=h0b31af3_0
  - libkml=1.3.0=hed7d534_1010
  - liblapack=3.8.0=16_openblas
  - liblapacke=3.8.0=16_openblas
  - libllvm8=8.0.1=h770b8ee_0
  - libnetcdf=4.6.2=h1a02027_1003
  - libopenblas=0.3.9=h3d69b6c_0
  - libpng=1.6.37=hbbe82c9_1
  - libpq=11.5=h756f0eb_1
  - libsodium=1.0.17=h01d97ff_0
  - libspatialindex=1.9.3=h4a8c4bd_3
  - libspatialite=4.3.0a=he369b6e_1029
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.1.0=ha78913b_3
  - libunistring=0.9.10=h1de35cc_0
  - libwebp=1.0.2=h20df551_3
  - libxml2=2.9.9=hd80cff7_2
  - llvm-openmp=9.0.1=h28b9765_2
  - llvmlite=0.31.0=py37hb548287_1
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=h6de7cb9_1001
  - markdown=3.2.1=py_0
  - markupsafe=1.1.1=py37h9bfed18_1
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37h3a684a6_1
  - mccabe=0.6.1=py_1
  - mercantile=1.1.2=py_0
  - mistune=0.8.4=py37h0b31af3_1000
  - mpld3=0.3=py_1
  - msgpack-python=0.6.2=py37ha1b3eb9_0
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=h0a44026_1002
  - netcdf4=1.5.1.2=py37h876e625_1
  - nettle=3.4.1=h3efe00b_1002
  - networkx=2.4=py_1
  - notebook=6.0.3=py37_0
  - numba=0.48.0=py37h4f17bb1_0
  - numpy=1.17.0=py37h6b0580a_0
  - olefile=0.46=py_0
  - opencv=4.1.1=py37hb60cc42_2
  - openh264=1.8.0=hd9629dc_1000
  - openjpeg=2.3.1=h254dc36_3
  - openssl=1.1.1g=h0b31af3_0
  - owslib=0.19.2=py_1
  - packaging=20.1=py_0
  - pandas=1.0.3=py37h94625e5_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - panel=0.6.2=0
  - param=1.9.3=py_0
  - parso=0.6.2=py_0
  - partd=1.1.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=h4a8c4bd_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - phantomjs=2.1.1=1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.0.0=py37hfd78ece_1
  - pip=19.2.2=py37_0
  - pixman=0.38.0=h01d97ff_1003
  - poppler=0.67.0=h16886b5_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=h25afefd_1
  - proj4=6.1.0=h2cc77ee_2
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - psutil=5.7.0=py37h9bfed18_1
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pyepsg=0.4.0=py_0
  - pygments=2.6.1=py_0
  - pykdtree=1.3.1=py37h10e2902_1003
  - pylint=2.4.4=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pyproj=2.2.1=py37h804dea5_0
  - pyqt=5.9.2=py37h2a560b1_4
  - pyrsistent=0.15.7=py37h9bfed18_1
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.6=h90870a6_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.4=pyh8c360ce_0
  - pywavelets=1.1.1=py37h3b54f70_0
  - pyyaml=5.3.1=py37h9bfed18_0
  - pyzmq=19.0.0=py37haec44b1_1
  - qt=5.9.7=h93ee506_2
  - qtconsole=4.7.1=py_0
  - qtpy=1.9.0=py_0
  - rasterio=1.0.28=py37h238e834_0
  - rasterstats=0.13.1=py_1
  - readline=8.0=hcfe32e1_0
  - requests=2.23.0=pyh8c360ce_2
  - rtree=0.9.4=py37h8526d28_1
  - scikit-image=0.15.0=py37h86efe34_2
  - scipy=1.4.1=py37h82752d6_0
  - seaborn=0.9.0=py_1
  - selenium=3.141.0=py37h1de35cc_1000
  - send2trash=1.5.0=py_0
  - setuptools=46.1.1=py37hc8dfbb8_0
  - shapely=1.6.4=py37h0567c5e_1006
  - simplejson=3.17.0=py37h0b31af3_0
  - sip=4.19.8=py37h0a44026_1000
  - six=1.14.0=py_1
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.30.1=h93121df_0
  - statsmodels=0.11.1=py37h9bfed18_1
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h9bfed18_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - typed-ast=1.4.1=py37h0b31af3_0
  - typing_extensions=3.7.4.1=py37hc8dfbb8_1
  - tzcode=2019a=h01d97ff_1002
  - urllib3=1.25.7=py37hc8dfbb8_1
  - utm=0.5.0=py_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h9bfed18_1
  - x264=1!152.20180806=h1de35cc_0
  - xarray=0.12.3=py_0
  - xerces-c=3.2.2=h4db8090_1003
  - xmltodict=0.12.0=py_0
  - xz=5.2.4=h0b31af3_1002
  - yaml=0.2.2=h0b31af3_1
  - zeromq=4.3.2=h6de7cb9_2
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.4=hed8d7c8_2
  - pip:
    - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
    - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
    - "--editable=git+https://github.com/dshean/imview.git#egg=imview"
    - "--editable=git+https://github.com/friedrichknuth/bare.git#egg=bare"
    - "--editable=git+https://github.com/friedrichknuth/driveanon.git#egg=driveanon"
    - appdirs==1.4.3
    - click==6.7
    - colorama==0.4.1
    - cursor==1.3.4
    - elevation==1.0.6
    - fasteners==0.15
    - future==0.17.1
    - halo==0.0.28
    - log-symbols==0.0.14
    - matplotlib-colorbar==0.3.7
    - matplotlib-scalebar==0.6.0
    - monotonic==1.5
    - salem==0.2.4
    - spinners==0.0.23
    - termcolor==1.1.0
    - wget==3.2

