name: hsfm_base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - affine=2.3.0=py_0
  - aiodns=2.0.0=py_2
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - aiohttp-client-cache=0.4.3=pyhd8ed1ab_0
  - aioredis=1.3.1=py_0
  - aiosqlite=0.17.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - async_retriever=0.2.2=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - awscli=1.19.35=py38h578d9bd_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=20.8b1=py_1
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - bokeh=1.3.4=py38_0
  - boost-cpp=1.74.0=h9359b55_0
  - boto3=1.17.35=pyhd8ed1ab_0
  - botocore=1.20.35=pyhd8ed1ab_0
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py38h497a2fe_1001
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.16.0=h9f066cc_1006
  - cartopy=0.18.0=py38h88488af_4
  - cattrs=1.8.0=pyhd8ed1ab_0
  - cchardet=2.1.7=py38h709712a_1
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.3=py38h1bdcb99_1
  - cfitsio=3.470=hb418390_7
  - cftime=1.5.0=py38hb5d20a5_0
  - chardet=4.0.0=py38h578d9bd_1
  - charls=2.1.0=he1b5a44_2
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - cmocean=2.0=py_3
  - colorama=0.4.3=py_0
  - colorcet=2.0.6=pyhd8ed1ab_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - contextily=1.0.1=py_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h497a2fe_3
  - dask=2021.8.1=pyhd8ed1ab_0
  - dask-core=2021.8.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datashader=0.11.1=pyh9f0ad1d_0
  - datashape=0.5.4=py_1
  - dbus=1.13.6=hfdff14a_1
  - debugpy=1.4.1=py38h709712a_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - descartes=1.1.0=py_4
  - distributed=2021.8.1=py38h578d9bd_0
  - docutils=0.15.2=py38h578d9bd_2
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=h9c3ff4c_0
  - ffmpeg=4.3.2=hca11adc_0
  - fiona=1.8.17=py38h676c6b2_1
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - fsspec=0.8.7=pyhd8ed1ab_0
  - gdal=3.1.3=py38h9edfc58_1
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.8.1=py_0
  - geopy=2.2.0=pyhd8ed1ab_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h5d11630_3
  - geoviews=1.6.6=py_1
  - geoviews-core=1.6.6=py_1
  - gettext=0.19.8.1=hf34092f_1004
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.66.1=he1b5a44_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.7.2=hb1ce69c_1
  - haversine=2.3.0=py_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - hiredis=1.1.0=py38h1e0a361_1
  - holoviews=1.12.7=pyh9f0ad1d_1
  - hvplot=0.6.0=pyh9f0ad1d_0
  - icu=67.1=he1b5a44_0
  - idna=3.1=pyhd3deb0d_0
  - imagecodecs=2020.5.30=py38h63741c2_4
  - imageio=2.9.0=py_0
  - importlib-metadata=4.7.1=py38h578d9bd_1
  - ipykernel=6.2.0=py38he5a9106_0
  - ipympl=0.6.3=pyhd8ed1ab_0
  - ipython=7.26.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.13.1=hbfbb72e_1002
  - jsoncpp=1.8.4=hc9558a2_1002
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38h578d9bd_6
  - jupyter_client=7.0.1=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - jxrlib=1.1=h7f98852_2
  - kealib=1.4.14=hcc255d8_2
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.17.2=h926e7f8_0
  - lame=3.100=h7f98852_1001
  - laszip=3.4.3=he1b5a44_1
  - laz-perf=2.1.0=py38h709712a_3
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.5=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcurl=7.71.1=hcdd3856_8
#  - libdap4=3.20.6=hd7c4107_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgdal=3.1.3=h670eac6_1
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libglib=2.66.1=h0dae87d_1
  - libgomp=11.1.0=hc902ee8_8
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h02e6976_1012
  - liblapack=3.9.0=11_linux64_openblas
  - liblapacke=3.9.0=11_linux64_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopencv=4.4.0=py38_3
  - libpng=1.6.37=h21135ba_2
  - libpq=12.3=h5513abc_2
  - librttopo=1.1.0=hb271727_4
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h6ec7341_0
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvmlite=0.36.0=py38h4630a5e_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=he1b5a44_3
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.3.2=py38h32f6830_1
  - matplotlib-base=3.3.2=py38h4d1ce4f_1
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1004
  - msgpack-python=1.0.2=py38h1fd1430_1
  - multidict=5.1.0=py38h497a2fe_1
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py38h578d9bd_3
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - nb_conda_kernels=2.3.1=py38h578d9bd_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.1.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - netcdf4=1.5.4=nompi_py38hec8b9af_103
  - nettle=3.6=he412f7d_0
  - networkx=2.6.2=pyhd8ed1ab_0
  - nitro=2.7.dev6=he1b5a44_3
  - notebook=6.4.3=pyha770c72_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numba=0.53.1=py38h8b71fd7_1
  - numpy=1.19.2=py38hf89b668_1
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.4.0=py38_3
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.3.1=hf7af979_3
  - openssl=1.1.1l=h7f98852_0
  - orjson=3.6.3=py38h497a2fe_0
  - owslib=0.24.1=pyhd8ed1ab_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.1.3=py38hc5bc63f_2
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - panel=0.6.4=0
  - param=1.9.3=py_0
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.45=h9c3ff4c_0
  - pdal=2.2.0=ha9435c1_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.0=py38h9776b28_0
  - pip=20.2.4=py_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=0.89.0=h669c267_1
  - poppler-data=0.4.10=0
  - postgresql=12.3=h8573dbc_2
  - proj=7.1.1=h966b41f_3
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd8ed1ab_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=4.4.0=py38h1cdfbd6_3
  - py3dep=0.11.1=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pycares=4.0.0=py38h497a2fe_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydantic=1.8.2=py38h497a2fe_0
  - pyepsg=0.4.0=py_0
  - pygeoogc=0.11.3=pyhd8ed1ab_0
  - pygeoutils=0.11.3=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38h56787f0_3
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.6=h852b56e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-forge=18.6.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyviz_comms=2.1.0=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h5c078b8_3
  - pyyaml=5.4.1=py38h497a2fe_1
  - pyzmq=22.2.1=py38h2035c66_0
  - qt=5.12.9=h1f2b2cb_0
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.10.0=pyhd8ed1ab_0
  - rasterio=1.1.7=py38h676c6b2_1
  - rasterstats=0.14.0=py_0
  - readline=8.1=h46c0cb4_0
  - regex=2021.8.21=py38h497a2fe_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-cache=0.7.4=pyhd8ed1ab_0
  - rioxarray=0.7.0=pyhd8ed1ab_0
  - rsa=4.7.2=pyh44b312d_0
  - rtree=0.9.7=py38h02d302b_2
  - s3fs=0.4.2=py_0
  - s3transfer=0.3.6=pyhd8ed1ab_0
  - scikit-image=0.17.2=py38hc5bc63f_3
  - scipy=1.5.2=py38hd648e70_2
  - seaborn=0.11.0=0
  - seaborn-base=0.11.0=py_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=57.4.0=py38h578d9bd_0
  - shapely=1.7.1=py38hc7361b7_1
  - simplejson=3.17.5=py38h497a2fe_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.36.0=h9cd32fc_0
  - statsmodels=0.12.2=py38h5c078b8_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.11.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tifffile=2020.10.1=py_0
  - tiledb=2.1.1=h47b529c_1
  - tk=8.6.11=h21135ba_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.0.5=py_0
  - typed-ast=1.4.3=py38h497a2fe_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzcode=2021a=h7f98852_2
  - url-normalize=1.4.3=pyhd8ed1ab_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - utm=0.6.0=pyh9f0ad1d_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - x264=1!161.3030=h7f98852_1
  - xarray=0.19.0=pyhd8ed1ab_1
  - xerces-c=3.2.3=hfe33f54_1
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xmltodict=0.12.0=py_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_5
  - zict=2.0.0=py_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
    - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
    - "--editable=git+https://github.com/dshean/imview.git#egg=imview"
    - "--editable=git+https://github.com/friedrichknuth/bare.git#egg=bare"
    - "--editable=git+https://github.com/friedrichknuth/driveanon.git#egg=driveanon"
    - beautifulsoup4==4.9.3
    - bs4==0.0.1
    - click==6.7
    - elevation==1.0.6
    - fasteners==0.15
    - future==0.18.2
    - matplotlib-colorbar==0.4.0
    - matplotlib-scalebar==0.6.2
#    - metashape==1.6.1
    - monotonic==1.5
    - soupsieve==2.0.1
    - wget==3.2
